User.create!({ name: "Test Name", email: "test@test.com", password: "password", password_confirmation: "password" })
User.create!({ name: "Next Name", email: "next@test.com", password: "password", password_confirmation: "password" })

Movie.create!({ title: "Star Wars", release_date: "1977", director: "George Lucas", overview: "It's Star Wars", poster_path: "https://m.media-amazon.com/images/I/81P3lDJbjCL._AC_SY450_.jpg" })
Movie.create!({ title: "Raiders of the Lost Ark", release_date: "1981", director: "Steven Speilberg", overview: "It's Indiana Jones", poster_path: "https://cdn.shopify.com/s/files/1/1057/4964/products/Raiders-of-the-Lost-Ark-Vintage-Movie-Poster-Original-1-Sheet-27x41-7519_7aadef65-2d21-4725-98c4-a30235764b87.jpg?v=1638648421" })
Movie.create!({ title: "Blade Runner", release_date: "1982", director: "Ridley Scott", overview: "It's Blade Runner", poster_path: "https://cdn.shopify.com/s/files/1/0057/3728/3618/products/803274d62004eb9144046c0cb0d188bd_5162e4aa-30b8-44f5-aa08-1ee481addd07_450x.jpg?v=1573585462" })
Movie.create!({ title: "The Dark Knight", release_date: "2008", director: "Christopher Nolan", overview: "It's Batman in Chicago", poster_path: "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_.jpg" })
Movie.create!({ title: "Spider-Man: Into The Spider-Verse", release_date: "2018", director: "Bob Persichetti", overview: "2 many Spidermans", poster_path: "https://m.media-amazon.com/images/M/MV5BMjMwNDkxMTgzOF5BMl5BanBnXkFtZTgwNTkwNTQ3NjM@._V1_.jpg" })
Movie.create!({ title: "The Grand Budapest Hotel", release_date: "2014", director: "Wes Anderson", overview: "It's not that I don't like it, I am physically repulsed", poster_path: "https://m.media-amazon.com/images/M/MV5BMzM5NjUxOTEyMl5BMl5BanBnXkFtZTgwNjEyMDM0MDE@._V1_FMjpg_UX1000_.jpg" })
Movie.create!({ title: "The Social Network", release_date: "2010", director: "David Fincher", overview: "You know what's cool? META!", poster_path: "https://miro.medium.com/max/712/1*stgfTdpOB56JoRePBapJCA.jpeg" })
Movie.create!({ title: "The Big Lebowski", release_date: "1998", director: "Joel Coen", overview: "Strong men also cry", poster_path: "https://m.media-amazon.com/images/M/MV5BNDQwMTAzOTkxNV5BMl5BanBnXkFtZTgwMjc0MTAwMjE@._V1_.jpg" })
Movie.create!({ title: "Goodfellas", release_date: "1990", director: "Martin Scorcese", overview: "Buddies hanging out and having fun", poster_path: "https://m.media-amazon.com/images/M/MV5BY2NkZjEzMDgtN2RjYy00YzM1LWI4ZmQtMjIwYjFjNmI3ZGEwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg" })
Movie.create!({ title: "Heat", release_date: "1995", director: "Michael Mann", overview: "We're here for the bank's money not your money", poster_path: "https://m.media-amazon.com/images/M/MV5BNGMwNzUwNjYtZWM5NS00YzMyLWI4NjAtNjM0ZDBiMzE1YWExXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_.jpg" })

UserMovie.create!({ movie_id: 1, user_id: 1, rank: 3 })
UserMovie.create!({ movie_id: 6, user_id: 1, rank: 4 })
UserMovie.create!({ movie_id: 9, user_id: 1, rank: 2 })
UserMovie.create!({ movie_id: 7, user_id: 1, rank: 1 })
UserMovie.create!({ movie_id: 5, user_id: 1, rank: 5 })
UserMovie.create!({ movie_id: 1, user_id: 2, rank: 1 })
UserMovie.create!({ movie_id: 10, user_id: 2, rank: 2 })
UserMovie.create!({ movie_id: 3, user_id: 2, rank: 4 })
UserMovie.create!({ movie_id: 2, user_id: 2, rank: 3 })
