User.create!({ name: "Kurt Proepper", email: "kurt@test.com", password: "password", password_confirmation: "password" })
User.create!({ name: "Bruce Wayne", email: "bat@test.com", password: "password", password_confirmation: "password" })
User.create!({ name: "Henry Hill", email: "mademan@test.com", password: "password", password_confirmation: "password" })
User.create!({ name: "Anikan Skywalker", email: "vader@test.com", password: "password", password_confirmation: "password" })
User.create!({ name: "The Dude", email: "bowling@test.com", password: "password", password_confirmation: "password" })

Movie.create!({ title: "Star Wars", release_date: "1977", director: "George Lucas", overview: "It's Star Wars", poster_path: "https://m.media-amazon.com/images/I/81P3lDJbjCL._AC_SY450_.jpg" })
Movie.create!({ title: "Raiders of the Lost Ark", release_date: "1981", director: "Steven Speilberg", overview: "It's Indiana Jones", poster_path: "https://cdn.shopify.com/s/files/1/1057/4964/products/Raiders-of-the-Lost-Ark-Vintage-Movie-Poster-Original-1-Sheet-27x41-7519_7aadef65-2d21-4725-98c4-a30235764b87.jpg?v=1638648421" })
Movie.create!({ title: "Blade Runner", release_date: "1982", director: "Ridley Scott", overview: "It's Blade Runner", poster_path: "https://cdn.shopify.com/s/files/1/0057/3728/3618/products/803274d62004eb9144046c0cb0d188bd_5162e4aa-30b8-44f5-aa08-1ee481addd07_450x.jpg?v=1573585462" })
Movie.create!({ title: "The Dark Knight", release_date: "2008", director: "Christopher Nolan", overview: "It's Batman in Chicago", poster_path: "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_.jpg" })
Movie.create!({ title: "Spider-Man: Into The Spider-Verse", release_date: "2018", director: "Bob Persichetti", overview: "2 many Spidermans", poster_path: "https://m.media-amazon.com/images/M/MV5BMjMwNDkxMTgzOF5BMl5BanBnXkFtZTgwNTkwNTQ3NjM@._V1_.jpg" })
Movie.create!({ title: "The Grand Budapest Hotel", release_date: "2014", director: "Wes Anderson", overview: "It's not that I don't like it, I am physically repulsed", poster_path: "https://m.media-amazon.com/images/M/MV5BMzM5NjUxOTEyMl5BMl5BanBnXkFtZTgwNjEyMDM0MDE@._V1_FMjpg_UX1000_.jpg" })
Movie.create!({ title: "The Social Network", release_date: "2010", director: "David Fincher", overview: "You know what's cool? META!", poster_path: "https://miro.medium.com/max/712/1*stgfTdpOB56JoRePBapJCA.jpeg" })
Movie.create!({ title: "The Big Lebowski", release_date: "1998", director: "Joel Coen", overview: "Strong men also cry", poster_path: "https://m.media-amazon.com/images/M/MV5BNDQwMTAzOTkxNV5BMl5BanBnXkFtZTgwMjc0MTAwMjE@._V1_.jpg" })
Movie.create!({ title: "Goodfellas", release_date: "1990", director: "Martin Scorcese", overview: "Buddies hanging out and having fun", poster_path: "https://m.media-amazon.com/images/M/MV5BY2NkZjEzMDgtN2RjYy00YzM1LWI4ZmQtMjIwYjFjNmI3ZGEwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg" })
Movie.create!({ title: "Heat", release_date: "1995", director: "Michael Mann", overview: "We're here for the bank's money not your money", poster_path: "https://m.media-amazon.com/images/M/MV5BNGMwNzUwNjYtZWM5NS00YzMyLWI4NjAtNjM0ZDBiMzE1YWExXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_.jpg" })
Movie.create!({ title: "Fellowship of the Ring", release_date: "2001", director: "Peter Jackson", overview: "Guys being dudes", poster_path: "https://m.media-amazon.com/images/I/81EBp0vOZZL._AC_SY741_.jpg" })
Movie.create!({ title: "Almost Famous", release_date: "2000", director: "Cameron Crowe", overview: "One day, you'll be cool", poster_path: "https://m.media-amazon.com/images/M/MV5BMzY1ZjMwMGEtYTY1ZS00ZDllLTk0ZmUtYzA3ZTA4NmYwNGNkXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_.jpg" })
Movie.create!({ title: "Casablanca", release_date: "1942", director: "Michael Curtiz", overview: "Didn't that movie used to have a war in it", poster_path: "https://i.insider.com/512cdb1eecad04742f000010" })
Movie.create!({ title: "Bull Durham", release_date: "1988", director: "Ron Shelton", overview: "You gotta play em one day at a time", poster_path: "https://m.media-amazon.com/images/M/MV5BMzMxMDEzMWUtZDk3NS00MWRiLWJjOGMtN2Q0ZjVhZjU3ODhkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_FMjpg_UX1000_.jpg" })
Movie.create!({ title: "Ferris Bueller's Day Off", release_date: "1986", director: "John Hughs", overview: "Cameron tries to ruin his fun friend's day", poster_path: "https://static.wikia.nocookie.net/ferrisbueller/images/6/65/Ferris_Bueller_film.jpg/revision/latest?cb=20200726000732" })
Movie.create!({ title: "Ocean's 11", release_date: "2001", director: "Steven Soderbergh", overview: "The coolest dudes just being cool", poster_path: "https://m.media-amazon.com/images/M/MV5BYzVmYzVkMmUtOGRhMi00MTNmLThlMmUtZTljYjlkMjNkMjJkXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_.jpg" })

UserMovie.create!({ movie_id: 1, user_id: 1, rank: 3 })
UserMovie.create!({ movie_id: 6, user_id: 1, rank: 4 })
UserMovie.create!({ movie_id: 9, user_id: 1, rank: 2 })
UserMovie.create!({ movie_id: 7, user_id: 1, rank: 1 })
UserMovie.create!({ movie_id: 5, user_id: 1, rank: 5 })
UserMovie.create!({ movie_id: 1, user_id: 2, rank: 1 })
UserMovie.create!({ movie_id: 10, user_id: 2, rank: 2 })
UserMovie.create!({ movie_id: 3, user_id: 2, rank: 4 })
UserMovie.create!({ movie_id: 4, user_id: 2, rank: 5 })
UserMovie.create!({ movie_id: 16, user_id: 3, rank: 1 })
UserMovie.create!({ movie_id: 11, user_id: 3, rank: 5 })
UserMovie.create!({ movie_id: 12, user_id: 3, rank: 2 })
UserMovie.create!({ movie_id: 8, user_id: 3, rank: 3 })
UserMovie.create!({ movie_id: 13, user_id: 3, rank: 4 })
UserMovie.create!({ movie_id: 2, user_id: 4, rank: 5 })
UserMovie.create!({ movie_id: 6, user_id: 4, rank: 4 })
UserMovie.create!({ movie_id: 7, user_id: 4, rank: 3 })
UserMovie.create!({ movie_id: 1, user_id: 4, rank: 2 })
UserMovie.create!({ movie_id: 13, user_id: 4, rank: 1 })
UserMovie.create!({ movie_id: 2, user_id: 5, rank: 4 })
UserMovie.create!({ movie_id: 14, user_id: 5, rank: 1 })
UserMovie.create!({ movie_id: 6, user_id: 5, rank: 3 })
UserMovie.create!({ movie_id: 11, user_id: 5, rank: 2 })
UserMovie.create!({ movie_id: 8, user_id: 5, rank: 5 })
